### ISSUE TITLE
Cannot find module 'chalk'

### ISSUE THREAD

**Issue by juwara0** [ciena-blueplanet/ember-test-utils#43]
In a consuming add-on, an error is displayed:

```
Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/Micarrol/Devel/ember-frost-date-picker/node_modules/ember-test-utils/cli/lint-all-the-things.js:3:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by juwara0** [comment]
Fixed in: https://github.com/ciena-blueplanet/ember-test-utils/pull/44
